# Generated by Django 2.0.4 on 2018-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='return_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
