# Generated by Django 2.0.4 on 2018-04-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180427_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='metadata',
            field=models.TextField(null=True),
        ),
    ]
